In [1]:
#Importing modules and libralies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [2]:
#Reading datasheet datas 
datas = pd.read_csv('Real-estate-data.csv')
table = datas.head()
maths = datas.describe()

In [3]:
#Short summury of contents in tabular form
print("\n\nThe following are the data statistical table:-\n\n")
print(table)



The following are the data statistical table:-


   No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391          

In [4]:
#Datas statistical calculations
print("\n\nThe folowing are the data mathematical calulations:-\n\n")
print(maths)



The folowing are the data mathematical calulations:-


               No  X1 transaction date  X2 house age  \
count  414.000000           414.000000    414.000000   
mean   207.500000          2013.148971     17.712560   
std    119.655756             0.281967     11.392485   
min      1.000000          2012.667000      0.000000   
25%    104.250000          2012.917000      9.025000   
50%    207.500000          2013.167000     16.100000   
75%    310.750000          2013.417000     28.150000   
max    414.000000          2013.583000     43.800000   

       X3 distance to the nearest MRT station  \
count                              414.000000   
mean                              1083.885689   
std                               1262.109595   
min                                 23.382840   
25%                                289.324800   
50%                                492.231300   
75%                               1454.279000   
max                               6488.021000 

In [5]:
#Datasheet informations summury
print("\n\nThe informations concerning the datas are:-\n\n")
data_info = datas.info()
print(data_info)



The informations concerning the datas are:-


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   No                                      414 non-null    int64  
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64  
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 25.9 KB
None


In [7]:
#The shape of the dataframe
print("\n\nThe shape of the dataframes is:\n")
frame_shape = datas.shape
print(frame_shape)



The shape of the dataframes is:

(414, 8)


In [8]:
#The number of variables in each datasheet
print("\n\nThe following are the number of variable in each data column:\n\n")
data_count = datas.count
print(data_count)



The following are the number of variable in each data column:


<bound method DataFrame.count of       No  X1 transaction date  X2 house age  \
0      1             2012.917          32.0   
1      2             2012.917          19.5   
2      3             2013.583          13.3   
3      4             2013.500          13.3   
4      5             2012.833           5.0   
..   ...                  ...           ...   
409  410             2013.000          13.7   
410  411             2012.667           5.6   
411  412             2013.250          18.8   
412  413             2013.000           8.1   
413  414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3               

In [9]:
#Datatype of each column
print("\n\nThe datatype of each column of the datasheet is:\n\n")
data_type = datas.dtypes
print(data_type)



The datatype of each column of the datasheet is:


No                                          int64
X1 transaction date                       float64
X2 house age                              float64
X3 distance to the nearest MRT station    float64
X4 number of convenience stores             int64
X5 latitude                               float64
X6 longitude                              float64
Y house price of unit area                float64
dtype: object


In [10]:
#Value of X to be plotted on the data training graph
print("\n\nThe graphical array values of X are:\n\n")
x = datas[['X1 transaction date','X2 house age','X3 distance to the nearest MRT station','X4 number of convenience stores','X5 latitude','X6 longitude']].values
print(x)



The graphical array values of X are:


[[2012.917     32.        84.87882   10.        24.98298  121.54024]
 [2012.917     19.5      306.5947     9.        24.98034  121.53951]
 [2013.583     13.3      561.9845     5.        24.98746  121.54391]
 ...
 [2013.25      18.8      390.9696     7.        24.97923  121.53986]
 [2013.         8.1      104.8101     5.        24.96674  121.54067]
 [2013.5        6.5       90.45606    9.        24.97433  121.5431 ]]


In [11]:
#Value of Y to be plotted on the data training graph
print("\n\nThe graphical array values of Y are:\n\n")
y = datas[['Y house price of unit area']].values
print(y)



The graphical array values of Y are:


[[ 37.9]
 [ 42.2]
 [ 47.3]
 [ 54.8]
 [ 43.1]
 [ 32.1]
 [ 40.3]
 [ 46.7]
 [ 18.8]
 [ 22.1]
 [ 41.4]
 [ 58.1]
 [ 39.3]
 [ 23.8]
 [ 34.3]
 [ 50.5]
 [ 70.1]
 [ 37.4]
 [ 42.3]
 [ 47.7]
 [ 29.3]
 [ 51.6]
 [ 24.6]
 [ 47.9]
 [ 38.8]
 [ 27. ]
 [ 56.2]
 [ 33.6]
 [ 47. ]
 [ 57.1]
 [ 22.1]
 [ 25. ]
 [ 34.2]
 [ 49.3]
 [ 55.1]
 [ 27.3]
 [ 22.9]
 [ 25.3]
 [ 47.7]
 [ 46.2]
 [ 15.9]
 [ 18.2]
 [ 34.7]
 [ 34.1]
 [ 53.9]
 [ 38.3]
 [ 42. ]
 [ 61.5]
 [ 13.4]
 [ 13.2]
 [ 44.2]
 [ 20.7]
 [ 27. ]
 [ 38.9]
 [ 51.7]
 [ 13.7]
 [ 41.9]
 [ 53.5]
 [ 22.6]
 [ 42.4]
 [ 21.3]
 [ 63.2]
 [ 27.7]
 [ 55. ]
 [ 25.3]
 [ 44.3]
 [ 50.7]
 [ 56.8]
 [ 36.2]
 [ 42. ]
 [ 59. ]
 [ 40.8]
 [ 36.3]
 [ 20. ]
 [ 54.4]
 [ 29.5]
 [ 36.8]
 [ 25.6]
 [ 29.8]
 [ 26.5]
 [ 40.3]
 [ 36.8]
 [ 48.1]
 [ 17.7]
 [ 43.7]
 [ 50.8]
 [ 27. ]
 [ 18.3]
 [ 48. ]
 [ 25.3]
 [ 45.4]
 [ 43.2]
 [ 21.8]
 [ 16.1]
 [ 41. ]
 [ 51.8]
 [ 59.5]
 [ 34.6]
 [ 51. ]
 [ 62.2]
 [ 38.2]
 [ 32.9]
 [ 54.4]
 [ 45.7]
 [ 30.5]
 [ 71. ]
 [ 47

In [12]:
#The array data shape of X datas
print("\n\nThe following is the array data shape of X values:\n")
x_shape = x.shape
print(x_shape)



The following is the array data shape of X values:

(414, 6)


In [13]:
#The array data shape of X datas
print("\n\nThe following is the array data shape of y values:\n")
y_shape = y.shape
print(y_shape)



The following is the array data shape of y values:

(414, 1)


In [14]:
#Making a model and determining an intercept and coefficient/gradient from the model's best fit line
model = LinearRegression()
model.fit(x,y)
coefficient = model.coef_
intercept = model.intercept_
print("\n\nFrom the best fit,the coefficient of the graph is:",coefficient)
print("\nFrom the best fit,the intercept of the graph is:",intercept)



From the best fit,the coefficient of the graph is: [[ 5.14622746e+00 -2.69695448e-01 -4.48746107e-03  1.13327690e+00
   2.25472976e+02 -1.24236012e+01]]

From the best fit,the intercept of the graph is: [-14437.10080228]


In [15]:
#Model training prediction
model_prediction = model.predict(x)
print("\n\nFrom the graphs model best fit, the price data prediction would be:\n\n")
print(model_prediction)



From the graphs model best fit, the price data prediction would be:


[[47.1689389 ]
 [47.82573429]
 [48.79677789]
 [48.36964101]
 [46.13886467]
 [31.13584564]
 [38.61587363]
 [46.85211217]
 [ 9.16603868]
 [34.77290915]
 [33.57234765]
 [53.09676524]
 [40.81426207]
 [26.94175908]
 [45.60486371]
 [38.10925895]
 [50.74281482]
 [37.18549698]
 [46.73342273]
 [47.53381528]
 [35.27726629]
 [49.46841634]
 [28.83473867]
 [47.85745455]
 [34.85705632]
 [31.97023446]
 [46.14266672]
 [42.09675228]
 [42.74715351]
 [45.6877317 ]
 [13.30333363]
 [40.52337885]
 [30.63871176]
 [46.3959655 ]
 [47.09156123]
 [33.19408286]
 [30.47381406]
 [30.84947324]
 [44.37062824]
 [45.87840415]
 [14.39995637]
 [16.50429405]
 [36.5591134 ]
 [40.18913549]
 [47.67033493]
 [39.75218341]
 [46.77260072]
 [37.498337  ]
 [12.6294391 ]
 [ 9.47655036]
 [41.79896601]
 [23.81663298]
 [34.86234689]
 [41.58762719]
 [45.47309058]
 [23.27524433]
 [43.40062271]
 [45.86319892]
 [13.52063193]
 [40.65937162]
 [34.01289788]
 [50.38387703

In [16]:
#Mean Square Error of the model prediction
print("\n\nThe mean squared error of the the model is:-")
mse = mean_squared_error(y,model_prediction)
sqr_mse = np.sqrt(mse)
print("{:.4f}".format(sqr_mse))



The mean squared error of the the model is:-
8.7825


In [17]:
#R2 score of the model prediction
print("\n\nThe model r2 score is:-")
model_r2_score = r2_score(y,model_prediction)
print("{:.4f}".format(model_r2_score))



The model r2 score is:-
0.5824


In [18]:
#Set Score of the model prediction
print("\n\nThe model trainig data set score is:-")
model_train_score = model.score(x,y)
print("{:.4f}".format(model_train_score))



The model trainig data set score is:-
0.5824


In [19]:
#Model and dataframe statistical and linear regression interpreted values table
print("\n\nThe following is the model statistical sumary table:")
model = sm.OLS(y, x).fit()
model.summary()



The following is the model statistical sumary table:


<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.952
Model:                            OLS   Adj. R-squared (uncentered):              0.951
Method:                 Least Squares   F-statistic:                              1351.
Date:                Wed, 16 Dec 2020   Prob (F-statistic):                   1.34e-265
Time:                        22:44:51   Log-Likelihood:                         -1489.3
No. Observations:                 414   AIC:                                      2991.
Df Residuals:                     408   BIC:                                      3015.
Df Model:                           6                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             3.7401      1.416      2.641      0.009       0.956       6.524
x2            -0.2708      0.039     -6.999      0.000      -0.347      -0.195
x3            -0.0055      0.001    -10.121      0.000      -0.007      -0.004
x4             1.1290      0.189      5.975      0.000       0.758       1.501
x5           203.3142     43.524      4.671      0.000     117.755     288.873
x6          -103.3604     23.311     -4.434      0.000    -149.185     -57.535
==============================================================================
Omnibus:                      223.806   Durbin-Watson:                   2.140
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3262.680
Skew:                           1.954   Prob(JB):                         0.00
Kurtosis:                      16.186   Cond. No.                     2.39e+05
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 2.39e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""